version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    platform: linux/amd64
    container_name: postgres_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin


  server:
    build: ./server
    platform: linux/amd64
    image: server-dock
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Europe/Moscow"

  gateway:
    build: ./gateway
    platform: linux/amd64
    image: gateway-dock
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090
      TZ: "Europe/Moscow"


